

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import factoryDAO.factoryDAO;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksidb;
import loginkasir.login;

/**
 *
 * @author USER
 */
public class ViewPembelian extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPembelian
     */
    factoryDAO facDAO = new factoryDAO();
    interfacetransaksi inpembelian = facDAO.getPembelianDAO();
    private final String[] tabelbeli;
    private DefaultTableModel tabelmodelbeli;
    private int baris;
    ResultSet rs;
    private int total = 0;
    private ArrayList tab = new ArrayList<>();
    koneksidb kon = new koneksidb();

    public ViewPembelian(login log) {
        initComponents();
        tabelbeli = new String[]{"Nama", "Jumlah", "Harga", "Sub Total"};
        tabelmodelbeli = new DefaultTableModel(null, tabelbeli);
        TabelBlanja.setModel(tabelmodelbeli);
        no();
        tgl();
        
        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        Tpegawai.setText(String.valueOf(log.getIdpegawai()));
    }

    protected final void tgl() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

        TTgl.setText(dateFormat.format(date));
        TWaktu.setText(timeFormat.format(date));

    }
    /**
     * Digunakan untuk mengambl nomer pembelian sekarang
     */
    public final void no() {

        try {

            koneksidb konek = new koneksidb();
            PreparedStatement pst = konek.getCon().prepareStatement(""
                    + "select notabeli as nt  from pembelian order by notabeli DESC limit 1");
            rs = pst.executeQuery();
            if (rs.next()) {
                int nota = Integer.parseInt(rs.getString("nt")) + 1;
                TNo.setText(Integer.toString(nota));
            } else {
                int nota = 1;
                TNo.setText(Integer.toString(nota));
            }
            rs.close();
        } catch (SQLException e) {
        }
        TJml.requestFocusInWindow();
    }

    private void bersih() {
        RBTunai.setEnabled(true);
        RBTunai.setSelected(false);
        RBKredit.setSelected(false);
        RBKredit.setEnabled(true);
        TKet.setText(null);
        TBarang.setText(null);
        TBayar.setText(null);
        TTOTAL.setText(null);
        TJml.setText(null);
        THarga.setText(null);
        TSubTot.setText(null);
        tabelmodelbeli.setRowCount(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TJml = new javax.swing.JTextField();
        THarga = new javax.swing.JTextField();
        TSubTot = new javax.swing.JTextField();
        BBeli = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TTgl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TWaktu = new javax.swing.JTextField();
        RBTunai = new javax.swing.JCheckBox();
        RBKredit = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        TKet = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Tpegawai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBlanja = new javax.swing.JTable();
        BBatal = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        TTOTAL = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        TBayar = new javax.swing.JTextField();
        BReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pembelian");

        jPanel1.setBackground(new java.awt.Color(195, 232, 251));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBELIAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        jLabel2.setText("No");

        TNo.setDisabledTextColor(new java.awt.Color(0, 0, 153));
        TNo.setEnabled(false);
        TNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Barang");

        TBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBarangActionPerformed(evt);
            }
        });
        TBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TBarangKeyPressed(evt);
            }
        });

        jLabel4.setText("Jumlah");

        jLabel5.setText("Harga");

        jLabel6.setText("Sub. Total");

        TJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TJmlKeyPressed(evt);
            }
        });

        THarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                THargaKeyPressed(evt);
            }
        });

        TSubTot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TSubTotKeyPressed(evt);
            }
        });

        BBeli.setText("Beli");
        BBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBeliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("X");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("=");

        jLabel9.setText("Tanggal");

        TTgl.setForeground(new java.awt.Color(255, 255, 255));
        TTgl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TTgl.setEnabled(false);

        jLabel10.setText("Waktu");

        TWaktu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TWaktu.setEnabled(false);

        RBTunai.setText("Tunai");
        RBTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTunaiActionPerformed(evt);
            }
        });

        RBKredit.setText("Kredit");
        RBKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKreditActionPerformed(evt);
            }
        });

        jLabel11.setText("Keterangan");

        TKet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TKetKeyPressed(evt);
            }
        });

        jLabel13.setText("Jenis Belanja");

        jLabel12.setText("Pegawai");

        Tpegawai.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(TWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tpegawai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TJml, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TSubTot, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel5)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BBeli)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(8, 8, 8)
                                .addComponent(RBTunai)
                                .addGap(50, 50, 50)
                                .addComponent(RBKredit))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(TKet, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RBTunai)
                                .addComponent(RBKredit))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(TWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(TKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(Tpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TSubTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BBeli)
                        .addGap(26, 26, 26))))
        );

        TabelBlanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barang", "Jumlah", "Harga", "Sub.Total"
            }
        ));
        jScrollPane1.setViewportView(TabelBlanja);

        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 10));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 0, 0));
        jLabel34.setText("TOTAL");

        TTOTAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TTOTAL.setForeground(new java.awt.Color(204, 0, 0));
        TTOTAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TTOTAL.setText("0");
        TTOTAL.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        TTOTAL.setEnabled(false);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("BAYAR");

        TBayar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TBayar.setForeground(new java.awt.Color(204, 0, 0));
        TBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TBayarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(TTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(TBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BBatal)
                        .addGap(18, 18, 18)
                        .addComponent(BSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(BReset)
                        .addGap(129, 129, 129)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BSimpan)
                        .addComponent(BBatal)
                        .addComponent(BReset)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoActionPerformed

    private void TBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBarangActionPerformed

    private void TBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBarangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if("".equals(TBarang.getText())){
                beli();
            }else{
            TJml.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_TBarangKeyPressed

    private void TJmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TJmlKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            THarga.requestFocusInWindow();
        }
    }//GEN-LAST:event_TJmlKeyPressed
    protected void beli() {

        int Jml = Integer.parseInt(TJml.getText());
        int Harga = Integer.parseInt(THarga.getText());
        int Sub = Integer.valueOf(TSubTot.getText());
        String Barang = TBarang.getText();

        total = (int) (total + Sub);
        TTOTAL.setText(String.valueOf(total));

        Object[] data = {Barang, Harga, Jml, Sub};

        tabelmodelbeli.addRow(data);
        TBarang.setText(null);
        THarga.setText(null);
        TJml.setText(null);
        TSubTot.setText(null);
        BSimpan.setEnabled(true);
    }
    private void THargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_THargaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("".equals(TSubTot.getText())) {
                transaksi tran = new transaksi();
                int Jml = Integer.parseInt(TJml.getText());
                int harga = Integer.parseInt(THarga.getText());
                int sub = 0;
                tran.setHarga(harga);
                tran.setJumlah(Jml);
                tran.hitung(Jml, harga, sub);

                TSubTot.setText(String.valueOf(tran.hitung(Jml, harga, sub)));
            } else {
                beli();
                TBarang.requestFocusInWindow();
            }

        }
    }//GEN-LAST:event_THargaKeyPressed

    private void TSubTotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TSubTotKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BBeli.requestFocusInWindow();
        }
    }//GEN-LAST:event_TSubTotKeyPressed

    private void BBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBeliActionPerformed
        // TODO add your handling code here:
        beli();
        BSimpan.setEnabled(true);
    }//GEN-LAST:event_BBeliActionPerformed

    private void RBTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTunaiActionPerformed
        // TODO add your handling code here:
        if (RBTunai.isSelected()) {
            RBKredit.setEnabled(false);
            TKet.requestFocusInWindow();
        }
    }//GEN-LAST:event_RBTunaiActionPerformed

    private void RBKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKreditActionPerformed
        // TODO add your handling code here:
        if (RBKredit.isSelected()) {
            RBTunai.setEnabled(false);
            TKet.requestFocusInWindow();
        }
    }//GEN-LAST:event_RBKreditActionPerformed

    private void TKetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKetKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TBarang.requestFocusInWindow();
        }
    }//GEN-LAST:event_TKetKeyPressed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        tabelmodelbeli.removeRow(0);
    }//GEN-LAST:event_BBatalActionPerformed

    private void simpan(){
        transaksi tran = new transaksi();
        int nota = Integer.parseInt(TNo.getText());
        int idPegawai = Integer.parseInt(Tpegawai.getText());
        String tanggal = TTgl.getText();
        String waktu = TWaktu.getText();
        String totalbeli = TTOTAL.getText();
        int bayar = Integer.parseInt(TBayar.getText());
        String keterangan = TKet.getText();
        String Jenis = "";
        if (RBKredit.isSelected()) {
            Jenis = "Kredit";
        } else if (RBTunai.isSelected()) {
            Jenis = "Tunai";
        } else {
            JOptionPane.showConfirmDialog(null, 
                    "MAAF, Uang Pilih Jenis Pembayaran Dulu !!",
                    "Pemberitahuan", JOptionPane.OK_CANCEL_OPTION);
        }
        tran.setIdpegawai(idPegawai);
        tran.setTgl(tanggal);
        tran.setWaktu(waktu);
        tran.setTotal(total);
        tran.setBayar(bayar);
        tran.setJenis(Jenis);
        tran.setKeterangan(keterangan);
        inpembelian.simpan(tran);
        for (int row = 0; row < TabelBlanja.getRowCount(); row++) {

            try {
                PreparedStatement st = kon.getCon().prepareStatement(""
                        + "insert into ayemtentrem.detail_beli "
                        + "(Barang, Jumlah, Harga, Sub_Total ,Nota_Beli) values("
                        + "?,?,?,?,?)");

                st.setString(1, TabelBlanja.getValueAt(row, 0).toString());
                st.setString(2, TabelBlanja.getValueAt(row, 1).toString());
                st.setString(3, TabelBlanja.getValueAt(row, 2).toString());
                st.setString(4, TabelBlanja.getValueAt(row, 3).toString());
                st.setString(5, TNo.getText());
                st.execute();
            } catch (SQLException ex) {
                Logger.getLogger(ViewPembelian.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
        bersih();
        no();
    }
    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int totall = Integer.parseInt(TTOTAL.getText());
            int tbayar = Integer.parseInt(TBayar.getText());
            String ket = TKet.getText();
            if (tbayar >= totall) {
                
                simpan();
            } else {
                int validasi = JOptionPane.showConfirmDialog(null, 
                        "MAAF, Uang Bayar Kurang !!", "Pemberitahuan", JOptionPane.OK_CANCEL_OPTION);
                TKet.setText(ket + " Kurang Bayar = " + (totall - tbayar));

            }
        }
    }//GEN-LAST:event_TBayarKeyPressed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        bersih();
    }//GEN-LAST:event_BResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //    new ViewPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BBeli;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSimpan;
    private javax.swing.JCheckBox RBKredit;
    private javax.swing.JCheckBox RBTunai;
    private javax.swing.JTextField TBarang;
    private javax.swing.JTextField TBayar;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField TJml;
    private javax.swing.JTextField TKet;
    private javax.swing.JTextField TNo;
    private javax.swing.JTextField TSubTot;
    private javax.swing.JTextField TTOTAL;
    private javax.swing.JTextField TTgl;
    private javax.swing.JTextField TWaktu;
    private javax.swing.JTable TabelBlanja;
    private javax.swing.JTextField Tpegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
