/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginkasir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import koneksi.koneksidb;
import laporan.LapPembelian;
import laporan.LapPenjualan;
import menu.ViewMenu;
import net.sf.jasperreports.engine.JasperCompileManager;
import pegawai.ViewPegawai;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import transaksi.ViewPembelian;
import transaksi.ViewPenjualan;

/**
 *
 * @author USER
 */
public class ViewHome extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    JInternalFrame FMenu, FPegawai, FPenjualan, FPembelian, FLJual, FLBeli;
    private Connection con;
    login log;
    JasperReport jaspor;
    JasperPrint jasprint;
    Map param = new HashMap();
    JasperDesign jasdes;

    public ViewHome(login log) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        koneksidb konek = new koneksidb();
        this.log = log;
        akses();
    }

    public boolean CekInternal(JInternalFrame form) {

        JInternalFrame frm[] = Deks.getAllFrames();

        boolean aktif = false;
        for (int i = 0; i < frm.length; i++) {
            if (frm[i].equals(form)) {
                aktif = true;
            }
        }
        return aktif;
    }

    public static void tengah(JInternalFrame form) {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - form.getSize().width) / 2;
        int y = (dim.height - form.getSize().height) / 2;
        form.setLocation(x, y);
    }
    private void akses() {
        try {
            koneksidb konek = new koneksidb();
            PreparedStatement pst = konek.getCon().prepareStatement(
                    "select Hak_Akses from pegawai where User=?");
            
            pst.setString(1, log.getUser());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) { //ambil record selanjutnya
                if (rs.getString(1).equalsIgnoreCase("Admin")) {//sama dengan admin=> beda besar kecil berpengaruh
                    MiPetugas.setEnabled(true);
                    MiMenu.setEnabled(true);
                    MiPenjualan.setEnabled(true);
                    MiPembelian.setEnabled(true);
                    LapPenjualan.setEnabled(true);
                    LapPembelian.setEnabled(true);
                    LapMenu.setEnabled(true);
                } else if (rs.getString(1).equalsIgnoreCase("Operator")){
                    MiPetugas.setEnabled(false); // petugas
                    MiMenu.setEnabled(false); // daftar menu
                    MiPenjualan.setEnabled(true);
                    MiPembelian.setEnabled(true);
                    LapPenjualan.setEnabled(false);
                    LapPembelian.setEnabled(false);
                    LapMenu.setEnabled(false);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deks = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MiMenu = new javax.swing.JMenuItem();
        MiPetugas = new javax.swing.JMenuItem();
        MTransaksi = new javax.swing.JMenu();
        MiPenjualan = new javax.swing.JMenuItem();
        MiPembelian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LapMenu = new javax.swing.JMenuItem();
        LapPenjualan = new javax.swing.JMenuItem();
        LapPembelian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Deks.setBackground(new java.awt.Color(255, 255, 255));
        Deks.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\kasir\\ayemtentrem\\src\\AYEMA.png")); // NOI18N
        Deks.add(jLabel3);
        jLabel3.setBounds(40, 20, 800, 230);

        jMenu1.setText("Master");

        MiMenu.setText("Daftar Menu");
        MiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiMenuActionPerformed(evt);
            }
        });
        jMenu1.add(MiMenu);

        MiPetugas.setText("Petugas");
        MiPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPetugasActionPerformed(evt);
            }
        });
        jMenu1.add(MiPetugas);

        jMenuBar1.add(jMenu1);

        MTransaksi.setText("Transaksi");

        MiPenjualan.setText("Penjualan");
        MiPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPenjualanActionPerformed(evt);
            }
        });
        MTransaksi.add(MiPenjualan);

        MiPembelian.setText("Pembelian");
        MiPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPembelianActionPerformed(evt);
            }
        });
        MTransaksi.add(MiPembelian);

        jMenuBar1.add(MTransaksi);

        jMenu3.setText("Laporan");

        LapMenu.setText("Menu");
        LapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapMenuActionPerformed(evt);
            }
        });
        jMenu3.add(LapMenu);

        LapPenjualan.setText("Penjualan");
        LapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(LapPenjualan);

        LapPembelian.setText("Pembelian");
        LapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(LapPembelian);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deks, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deks, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiMenuActionPerformed
        // TODO add your handling code here:
        if (CekInternal(FMenu) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FMenu = new ViewMenu();
            FMenu.setVisible(true);
            tengah(FMenu);
            Deks.add(FMenu);
            try {
                FMenu.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_MiMenuActionPerformed

    private void MiPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPetugasActionPerformed
        // TODO add your handling code here:
        if (CekInternal(FPegawai) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FPegawai = new ViewPegawai();
            FPegawai.setVisible(true);
            tengah(FPegawai);
            Deks.add(FPegawai);
            try {
                FPegawai.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_MiPetugasActionPerformed

    private void LapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPenjualanActionPerformed
        if (CekInternal(FLJual) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FLJual = new LapPenjualan();
            FLJual.setVisible(true);
            tengah(FLJual);
            Deks.add(FLJual);
            try {
                FLJual.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_LapPenjualanActionPerformed

    private void MiPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPenjualanActionPerformed

        if (CekInternal(FPenjualan) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FPenjualan = new ViewPenjualan(this.log);
            FPenjualan.setVisible(true);
            tengah(FPenjualan);
            Deks.add(FPenjualan);
            try {
                FPenjualan.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_MiPenjualanActionPerformed

    private void LapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapMenuActionPerformed

        try {
            koneksidb kon = new koneksidb();

            File file = new File("./src/laporan/LapMenu.jrxml");
            jasdes = JRXmlLoader.load(file);
            param.clear();
            jaspor = JasperCompileManager.compileReport(jasdes);
            jasprint = JasperFillManager.fillReport(jaspor, param, kon.getCon());
            JasperViewer.viewReport(jasprint, false);
            setVisible(true);
            setSize(840, 450);
        } catch (Exception ex) {
            Logger.getLogger(ViewHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LapMenuActionPerformed

    private void MiPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPembelianActionPerformed
        if (CekInternal(FPembelian) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FPembelian = new ViewPembelian(this.log);
            FPembelian.setVisible(true);
            tengah(FPembelian);
            Deks.add(FPembelian);
            try {
                FPembelian.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_MiPembelianActionPerformed

    private void LapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPembelianActionPerformed
        if (CekInternal(FLBeli) == true) {
            JOptionPane.showMessageDialog(null,
                    "Form Telah Aktif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            FLBeli = new LapPembelian();
            FLBeli.setVisible(true);
            tengah(FLBeli);
            Deks.add(FLBeli);
            try {
                FLBeli.setSelected(true);
            } catch (PropertyVetoException e) {
            }
        }
    }//GEN-LAST:event_LapPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //    new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane Deks;
    private javax.swing.JMenuItem LapMenu;
    private javax.swing.JMenuItem LapPembelian;
    private javax.swing.JMenuItem LapPenjualan;
    private javax.swing.JMenu MTransaksi;
    private javax.swing.JMenuItem MiMenu;
    private javax.swing.JMenuItem MiPembelian;
    private javax.swing.JMenuItem MiPenjualan;
    private javax.swing.JMenuItem MiPetugas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
