/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pegawai;

import factoryDAO.factoryDAO;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksidb;

/**
 *
 * @author USER
 */
public class ViewPegawai extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPetugas
     */
    private List<pegawai> listpegawai;
    private final String[] tabele;
    private DefaultTableModel tabelmodel;
    private boolean updSQLFlag = false;
    private int baris;
    ResultSet rs;
    factoryDAO facDAO = new factoryDAO();
    interfacepegawai inpegawai = facDAO.getPegawaiDAO();
    
    public ViewPegawai() {
        initComponents();
        koneksidb konek = new koneksidb();
        tabele = new String[]{"ID","User", "Nama", "Akses", "No Hp", "Alamat"};
        tabelmodel = new DefaultTableModel(null, tabele);
        TDaftarP.setModel(tabelmodel);
        TUser.setEnabled(false);
        TPass.setEnabled(false);
        tampilpegawai();
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
    }
    
    private void tampilpegawai() {
        listpegawai = inpegawai.tampilpegawai();
        tabelmodel = (DefaultTableModel) TDaftarP.getModel();
        tabelmodel.setRowCount(0);
        
        for (pegawai dpegawai : listpegawai) {
            tabelmodel.addRow(new Object[]{dpegawai.getIdpegawai(),
                dpegawai.getUser(), dpegawai.getNama(),
                dpegawai.getAkses(), dpegawai.getNohp(), dpegawai.getAlamat()});
            
        }
        int ambilbaris = TDaftarP.getRowCount();
        if (ambilbaris > 0) {
            TDaftarP.addRowSelectionInterval(0, 0);
        }
    }
    
    protected void aktif() {
        
        TNama.setEnabled(true);
        TNo.setEnabled(true);
        CBAkses.setEnabled(true);
        TAlamat.setEnabled(true);
    }
    
    protected void pasif() {
        
        TNama.setEnabled(false);
        TNo.setEnabled(false);
        CBAkses.setEnabled(false);
        TAlamat.setEnabled(false);
    }
    
    protected void bersih() {
        
        TNama.setText(null);
        TNo.setText(null);
        CBAkses.setSelectedIndex(0);
        TAlamat.setText(null);
        TUser.setText(null);
        TPass.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TUser = new javax.swing.JTextField();
        TNama = new javax.swing.JTextField();
        TNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBAkses = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAlamat = new javax.swing.JTextArea();
        TPass = new javax.swing.JTextField();
        Tid = new javax.swing.JTextField();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BTambah = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDaftarP = new javax.swing.JTable();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pegawai");

        jPanel1.setBackground(new java.awt.Color(195, 232, 251));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        jLabel1.setText("User");

        jLabel2.setText("Nama");

        jLabel3.setText("No Telepon");

        jLabel4.setText("Password");

        TUser.setEnabled(false);
        TUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUserActionPerformed(evt);
            }
        });
        TUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TUserKeyPressed(evt);
            }
        });

        TNama.setEnabled(false);
        TNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNamaKeyPressed(evt);
            }
        });

        TNo.setEnabled(false);
        TNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNoKeyPressed(evt);
            }
        });

        jLabel6.setText("Hak Akses");

        CBAkses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Pilih Hak Akses---", "Operator", "Admin" }));
        CBAkses.setEnabled(false);
        CBAkses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBAksesMouseClicked(evt);
            }
        });

        jLabel5.setText("Alamat");

        TAlamat.setColumns(20);
        TAlamat.setRows(5);
        TAlamat.setEnabled(false);
        jScrollPane2.setViewportView(TAlamat);

        TPass.setEnabled(false);

        Tid.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TPass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addComponent(CBAkses, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TUser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BHapus.setText("Hapus");
        BHapus.setEnabled(false);
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PETUGAS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Petugas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        TDaftarP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User", "Nama", "Akses", "Password", "No Hp", "Alamat"
            }
        ));
        TDaftarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TDaftarPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TDaftarP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BEdit.setText("Edit");
        BEdit.setEnabled(false);
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });

        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(BTambah)
                        .addGap(18, 18, 18)
                        .addComponent(BSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(BEdit)
                        .addGap(21, 21, 21)
                        .addComponent(BHapus)
                        .addGap(18, 18, 18)
                        .addComponent(BBatal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan)
                    .addComponent(BHapus)
                    .addComponent(BTambah)
                    .addComponent(BEdit)
                    .addComponent(BBatal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TDaftarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TDaftarPMouseClicked
        tampiltext();
        BEdit.setEnabled(true);
        BHapus.setEnabled(true);
    }//GEN-LAST:event_TDaftarPMouseClicked

    private void TUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TUserKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TUserKeyPressed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        pegawai pgw = new pegawai();
        String nama = TNama.getText();
        String no = TNo.getText();
        String alamat = TAlamat.getText();
        String akses = CBAkses.getSelectedItem().toString();
        Integer passwd = TPass.getText().hashCode();
        String user = TUser.getText();
        pgw.setUser(user);
        pgw.setAkses(akses);
        pgw.setAlamat(alamat);
        pgw.setNama(nama);
        pgw.setNohp(no);
        pgw.setPassword(passwd.toString());
        //elum ada set password sayang
        if (updSQLFlag == false) {
            if (nama.equals("") && no.equals("") && alamat.equals("") 
                    && akses.equals("---Pilih Hak Akses---")) {
                JOptionPane.showMessageDialog(null, "Data Harus Diisi Lengkap !",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                TNama.grabFocus();
            } else {
                inpegawai.simpan(pgw);
            }            
            tampilpegawai();
        }
        bersih();
        pasif();
        BSimpan.setEnabled(false);
    }//GEN-LAST:event_BSimpanActionPerformed
    
    final public void tampiltext() {
        baris = TDaftarP.getSelectedRow();
        if (baris >= 0) {
            Tid.setText(tabelmodel.getValueAt(baris, 0).toString());
            TUser.setText(tabelmodel.getValueAt(baris, 1).toString());
            TNama.setText(tabelmodel.getValueAt(baris, 2).toString());
            CBAkses.setSelectedItem(tabelmodel.getValueAt(baris, 3));
            TNo.setText(tabelmodel.getValueAt(baris, 4).toString());
            TAlamat.setText(tabelmodel.getValueAt(baris, 5).toString());
        }
    }
    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        pegawai pgw = new pegawai();
        String user = TUser.getText();
        pgw.setUser(user);
        if (TDaftarP.getRowCount() >= 0) {
            int reply = JOptionPane.showConfirmDialog(null, "Apakah Anda Akan Menghapus Data "+user,
                    "konfirmasi", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                inpegawai.hapus(pgw);
                int baris = TDaftarP.getRowCount();
                if (baris > 0) {
                    tabelmodel.removeRow(TDaftarP.getSelectedRow());
                }
                int row = TDaftarP.getRowCount();
                if (row == 0) {
                    
                }
            }
        }
        bersih();
        BEdit.setEnabled(false);
        BHapus.setEnabled(false);
    }//GEN-LAST:event_BHapusActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:

        aktif();
        TNama.requestFocusInWindow();
        BSimpan.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void TUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUserActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TUserActionPerformed

    private void TNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TNo.requestFocusInWindow();
        }
    }//GEN-LAST:event_TNamaKeyPressed

    private void TNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TAlamat.requestFocusInWindow();
        }

    }//GEN-LAST:event_TNoKeyPressed

    private void CBAksesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBAksesMouseClicked
        String nama = TNama.getText();
        String no = TNo.getText();
        String alamat = TAlamat.getText();
        if (updSQLFlag == false) {
            if (nama.equals("") && no.equals("") && alamat.equals("")) {
                JOptionPane.showMessageDialog(
                        null, "Data Harus Diisi Lengkap !", "Informasi", 
                        JOptionPane.INFORMATION_MESSAGE);
                TNama.grabFocus();
            } else {
                String user = "at" + nama.substring(1, 3) +
                        no.substring(9, 12) + alamat.subSequence(3, 5);
                TUser.setText(user);
                
                String pass = no.substring(5, 9) + "T" +
                        nama.substring(3, 6) + "A" + alamat.substring(3, 7);
                TPass.setText(pass);
            }
        }
        

    }//GEN-LAST:event_CBAksesMouseClicked

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        
        pegawai pgw = new pegawai();
        String nama = TNama.getText();
        String no = TNo.getText();
        String alamat = TAlamat.getText();
        String akses = CBAkses.getSelectedItem().toString();
        int idp = Integer.parseInt(Tid.getText());
        pgw.setIdpegawai(idp);
        pgw.setAkses(akses);
        pgw.setAlamat(alamat);
        pgw.setNama(nama);
        pgw.setNohp(no);
        
        if (TNama.isEnabled()) {
            if (updSQLFlag == false) {
                if (nama.equals("") && no.equals("") && alamat.equals("") && akses.equals("---Pilih Hak Akses---")) {
                    JOptionPane.showMessageDialog(null, "Data Harus Diisi Lengkap !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    TNama.grabFocus();
                } else {
                    inpegawai.edit(pgw);
                }
                tampilpegawai();
                BEdit.setEnabled(false);
                pasif();
                bersih();
            }
        } else {
            aktif();
        }
        BSimpan.setEnabled(false);
        BHapus.setEnabled(false);
    }//GEN-LAST:event_BEditActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        pasif();
        bersih();
        BSimpan.setEnabled(false);
        BEdit.setEnabled(false);
        BHapus.setEnabled(false);
        
    }//GEN-LAST:event_BBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBAkses;
    private javax.swing.JTextArea TAlamat;
    private javax.swing.JTable TDaftarP;
    private javax.swing.JTextField TNama;
    private javax.swing.JTextField TNo;
    private javax.swing.JTextField TPass;
    private javax.swing.JTextField TUser;
    private javax.swing.JTextField Tid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
